python mec.py --num-ue 5 --F 1 >> log_q_2.txt 
python mec.py --num-ue 5 --F 2 >> log_q_2.txt
python mec.py --num-ue 5 --F 3 >> log_q_2.txt
python mec.py --num-ue 5 --F 4 >> log_q_2.txt
python mec.py --num-ue 5 --F 5 >> log_q_2.txt
python mec.py --num-ue 5 --F 6 >> log_q_2.txt
python mec.py --num-ue 5 --F 7 >> log_q_2.txt
python mec.py --num-ue 5 --F 8 >> log_q_2.txt
python mec.py --num-ue 5 --F 9 >> log_q_2.txt
python mec.py --num-ue 5 --F 10 >> log_q_2.txt
